server:
  port: 7090
  servlet:
    context-path: /auth
jwt:
  auth:
    converter:
      resource-id: authenticationClientId
keycloak:
  realm: bisky-music
  domain: localhost:9081
  adminClientId: admin-cli
  adminClientSecret: qudNJ1ou1MS4UnRZog77QsfBd6Zs7GlT
  client: authenticationClientId
  urls:
    auth: http://${keycloak.domain}
spring:
  profile:
    active: production
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://${keycloak.domain}/realms/${keycloak.realm}
